Move ApiDomain to global section of the config (Issue #36)
microsoft/CEDAR.GitHub.Collector pull request #63
Opened 2021-01-05 19:05 UTC by myles-mcleroy

This commit moves the API domain from `local.settings.json` to `Settings.json`. To do so, I added two methods to the ConfigManager (GetApiDomainToken() and GetApiDomain()). In the setup of ConfigManager I created a map from the DefaultKey to the ApiDomainToken. I also increased coverage in ConfigManagerTests and GithubConfigManagerTests.

Since this is my first change to the repository, I wasn't 100% confident on where I should implement these changes (ConfigManager or GithubConfigManager), or the best way to do so (such as using a map instead of a plain string, or using try/catch to handle returning the apiDomain as a string). I'm open to suggestions on improving my code and more than happy to move things around.

2021-01-05 19:08 UTC, myles-mcleroy commented
I don't see my changes to `ConfigManager`. Let me update the commit.

2021-01-05 19:16 UTC, myles-mcleroy commented
My changes to `ConfigManager` and `ConfigManagerTests` are in `CEDAR.Core.Collector` under [this](https://github.com/microsoft/CEDAR.Core.Collector/pull/35) pull request.

2021-01-05 20:58 UTC, kivancmuslu requested changes
I think you need to also update all Ring configurations to have proper API domain values, could you please check?

2021-01-05 20:58 UTC, kivancmuslu commented on GitHub.Collectors.Functions/Settings.template.json
> -{
Wondering, why did you delete this file?

2021-01-05 20:58 UTC, kivancmuslu commented on GitHub.Collectors.Functions/Settings.barebones.template.json
> +    "ApiDomain":  "api.github.com"
We need this to be added to all Ring configurations as well, right (to the actual production deployment)?

2021-01-06 19:19 UTC, kivancmuslu commented on GitHub.Collectors.Functions/Settings.barebones.template.json
> +    "ApiDomain":  "api.github.com"
I believe this is resolved, right (in the ADO side)?

2021-01-07 06:34 UTC, kivancmuslu approved these changes
:shipit:

2021-01-07 14:54 UTC, merged